### PR TITLE
Add reference to endorsements. Add more badges

### PR DESCRIPTION
**Pull request by OleksiyRudenko**
* Change students' achievements endorsement badge links so those refer to `kottans/kottans/endorsements.md`
  Relates to https://github.com/kottans/kottans/pull/1
* Update instructions on endorsements
* Add badges: 'Kottans Evangelist', 'Kottans promoter'

[preview render](https://github.com/kottans/artifacts/blob/ef633feb72a4b49840c793f53f6c197aa3958c9a/badges.md)

Any suggestions as to colors on General purpose and Course badges?

Variations:

[Kottans-Evangelist%3D-Kottans%20Evangelist-lightgrey.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-00bfff.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-6495ed.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-blue.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-00ced1.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-20b2aa.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-006400.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-dc143c.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-c71585.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-ff00ff.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-da70d6.svg)](https://github.com/kottans)

### CODE REVIEW

**Review by yevhenorlov — APPROVED** [review]
thanks @OleksiyRudenko , great job as always 👍

**Comment by yevhenorlov** [comment]
Regarding colors of the badges: IMO specific color doesn't matter as long as it adheres to accessibility standards (color of text vs background). 
This tool might help - it provides a reasonable palette with specific accessibility scores for color combos: https://material.io/tools/color

**Comment by OleksiyRudenko** [comment]
@yevhenorlov Thank you!
I am a bit authorship-blind. At your taste what color variations quoted in initial post would match accessibility standards the best? Let's stick to top-3.

**Comment by yevhenorlov** [comment]
@OleksiyRudenko these ones seem to be more readable than the others

[Kottans-Evangelist%3D-Kottans%20Evangelist-blue.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-006400.svg)](https://github.com/kottans)

[Kottans-Evangelist%3D-Kottans%20Evangelist-dc143c.svg)](https://github.com/kottans)

**Review by suchov — APPROVED** [review]

**Comment by suchov** [comment]
Let's do the red one for the coolest one ;)

**Pull request merged**
